### PR TITLE
Patch AutoDiffScalar

### PR DESCRIPTION
**Pull request by tkoolen**
This adds a patch step to the ExternalProject_Add call. The patch fixes some bugs in AutoDiffScalar:
* [AutoDiffScalar atan2 function wrong](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=702) - fixed in 2013; it's kind of strange that this isn't included in 3.2.5. It is included in their 3.3 alpha release though.
* [Trying to compute AutoDiff Hessians results in an assertion error](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1063) - was reported on a forum somewhere but never fixed. I reported the bug, but they haven't responded yet.
* [AutoDiffScalar with fixed maximum size derivative type: certain operations don't work](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1070) - I found the fix for this today and reported the bug.

For reference, I created the patch by running
```
diff -Naur unsupported/Eigen/src/AutoDiff/AutoDiffScalar.h ~/Desktop/AutoDiffScalar.h > AutoDiffScalarPatch.patch
```
from the eigen root directory.

### CODE REVIEW

**Comment by RussTedrake** [comment]
patch adds an extremely gross dependency on non-cygwin windows.  see the bottom of https://github.com/RobotLocomotion/drake/wiki/Windows . i think we should avoid the patch.exe call if at all possible.

**Comment by tkoolen** [comment]
OK, I can just copy the fixed version of AutoDiffScalar over using cmake -E copy.

**Comment by RussTedrake** [comment]
that’s much better i think.

**Comment by RussTedrake** [comment]
sadly.

**Comment by tkoolen** [comment]
done.

**Pull request merged**
